variables:
  # Replace this name with that of the Azure service connection in your DevOps project
  ConnectedServiceName: 'Azure Primary'

  # Replace this name to match the name of the App Service you created earlier
  WebAppName: 'Flask Pipelines'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
